package main

import "strings"

var ShakespeareWiki = strings.Split(
	`William Shakespeare (bapt. 26 April 1564 – 23 April 1616)[a] was an English poet, playwright and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist.[2][3][4] He is often called England's national poet and the "Bard of Avon".[5][b] His extant works, including collaborations, consist of approximately 39 plays,[c] 154 sonnets, two long narrative poems, and a few other verses, some of uncertain authorship. His plays have been translated into every major living language and are performed more often than those of any other playwright.[7] 
Shakespeare was born and raised in Stratford-upon-Avon, Warwickshire. At the age of 18, he married Anne Hathaway, with whom he had three children: Susanna and twins Hamnet and Judith. Sometime between 1585 and 1592, he began a successful career in London as an actor, writer, and part-owner of a playing company called the Lord Chamberlain's Men, later known as the King's Men. At age 49 (around 1613), he appears to have retired to Stratford, where he died three years later. Few records of Shakespeare's private life survive; this has stimulated considerable speculation about such matters as his physical appearance, his sexuality, his religious beliefs, and whether the works attributed to him were written by others.[8][9][10] Such theories are often criticised for failing to adequately note that few records survive of most commoners of the period. 
Shakespeare produced most of his known works between 1589 and 1613.[11][12][d] His early plays were primarily comedies and histories and are regarded as some of the best work produced in these genres. Until about 1608, he wrote mainly tragedies, among them Hamlet, Othello, King Lear, and Macbeth, all considered to be among the finest works in the English language.[2][3][4] In the last phase of his life, he wrote tragicomedies (also known as romances) and collaborated with other playwrights. 
Many of Shakespeare's plays were published in editions of varying quality and accuracy in his lifetime. However, in 1623, two fellow actors and friends of Shakespeare's, John Heminges and Henry Condell, published a more definitive text known as the First Folio, a posthumous collected edition of Shakespeare's dramatic works that included all but two of his plays.[13] The volume was prefaced with a poem by Ben Jonson, in which Jonson presciently hails Shakespeare in a now-famous quote as "not of an age, but for all time".[13] 
Throughout the 20th and 21st centuries, Shakespeare's works have been continually adapted and rediscovered by new movements in scholarship and performance. His plays remain popular and are studied, performed, and reinterpreted through various cultural and political contexts around the world. 

Life
Main article: Life of William Shakespeare
Early life
William Shakespeare was the son of John Shakespeare, an alderman and a successful glover (glove-maker) originally from Snitterfield, and Mary Arden, the daughter of an affluent landowning farmer.[14] He was born in Stratford-upon-Avon and baptised there on 26 April 1564. His actual date of birth remains unknown, but is traditionally observed on 23 April, Saint George's Day.[15] This date, which can be traced to a mistake made by an 18th-century scholar, has proved appealing to biographers because Shakespeare died on the same date in 1616.[16][17] He was the third of eight children, and the eldest surviving son.[18] 
 

John Shakespeare's house, believed to be Shakespeare's birthplace, in Stratford-upon-Avon
Although no attendance records for the period survive, most biographers agree that Shakespeare was probably educated at the King's New School in Stratford,[19][20][21] a free school chartered in 1553,[22] about a quarter-mile (400 m) from his home. Grammar schools varied in quality during the Elizabethan era, but grammar school curricula were largely similar: the basic Latin text was standardised by royal decree,[23][24] and the school would have provided an intensive education in grammar based upon Latin classical authors.[25] 
At the age of 18, Shakespeare married 26-year-old Anne Hathaway. The consistory court of the Diocese of Worcester issued a marriage licence on 27 November 1582. The next day, two of Hathaway's neighbours posted bonds guaranteeing that no lawful claims impeded the marriage.[26] The ceremony may have been arranged in some haste since the Worcester chancellor allowed the marriage banns to be read once instead of the usual three times,[27][28] and six months after the marriage Anne gave birth to a daughter, Susanna, baptised 26 May 1583.[29] Twins, son Hamnet and daughter Judith, followed almost two years later and were baptised 2 February 1585.[30] Hamnet died of unknown causes at the age of 11 and was buried 11 August 1596.[31] 
 

Shakespeare's coat of arms, as it appears on the rough draft of the application to grant a coat-of-arms to John Shakespeare. It features a spear as a pun on the family name.[e]
After the birth of the twins, Shakespeare left few historical traces until he is mentioned as part of the London theatre scene in 1592. The exception is the appearance of his name in the "complaints bill" of a law case before the Queen's Bench court at Westminster dated Michaelmas Term 1588 and 9 October 1589.[32] Scholars refer to the years between 1585 and 1592 as Shakespeare's "lost years".[33] Biographers attempting to account for this period have reported many apocryphal stories. Nicholas Rowe, Shakespeare's first biographer, recounted a Stratford legend that Shakespeare fled the town for London to escape prosecution for deer poaching in the estate of local squire Thomas Lucy. Shakespeare is also supposed to have taken his revenge on Lucy by writing a scurrilous ballad about him.[34][35] Another 18th-century story has Shakespeare starting his theatrical career minding the horses of theatre patrons in London.[36] John Aubrey reported that Shakespeare had been a country schoolmaster.[37] Some 20th-century scholars have suggested that Shakespeare may have been employed as a schoolmaster by Alexander Hoghton of Lancashire, a Catholic landowner who named a certain "William Shakeshafte" in his will.[38][39] Little evidence substantiates such stories other than hearsay collected after his death, and Shakeshafte was a common name in the Lancashire area.[40][41] 
London and theatrical career
It is not known definitively when Shakespeare began writing, but contemporary allusions and records of performances show that several of his plays were on the London stage by 1592.[42] By then, he was sufficiently known in London to be attacked in print by the playwright Robert Greene in his Groats-Worth of Wit: 
... there is an upstart Crow, beautified with our feathers, that with his Tiger's heart wrapped in a Player's hide, supposes he is as well able to bombast out a blank verse as the best of you: and being an absolute Johannes factotum, is in his own conceit the only Shake-scene in a country.[43]
Scholars differ on the exact meaning of Greene's words,[43][44] but most agree that Greene was accusing Shakespeare of reaching above his rank in trying to match such university-educated writers as Christopher Marlowe, Thomas Nashe, and Greene himself (the so-called "University Wits").[45] The italicised phrase parodying the line "Oh, tiger's heart wrapped in a woman's hide" from Shakespeare's Henry VI, Part 3, along with the pun "Shake-scene", clearly identify Shakespeare as Greene's target. As used here, Johannes Factotum ("Jack of all trades") refers to a second-rate tinkerer with the work of others, rather than the more common "universal genius".[43][46] 
Greene's attack is the earliest surviving mention of Shakespeare's work in the theatre. Biographers suggest that his career may have begun any time from the mid-1580s to just before Greene's remarks.[47][48][49] After 1594, Shakespeare's plays were performed only by the Lord Chamberlain's Men, a company owned by a group of players, including Shakespeare, that soon became the leading playing company in London.[50] After the death of Queen Elizabeth in 1603, the company was awarded a royal patent by the new King James I, and changed its name to the King's Men.[51] 
"All the world's a stage,
and all the men and women merely players:
they have their exits and their entrances;
and one man in his time plays many parts ..." 
—As You Like It, Act II, Scene 7, 139–142[52]
In 1599, a partnership of members of the company built their own theatre on the south bank of the River Thames, which they named the Globe. In 1608, the partnership also took over the Blackfriars indoor theatre. Extant records of Shakespeare's property purchases and investments indicate that his association with the company made him a wealthy man,[53] and in 1597, he bought the second-largest house in Stratford, New Place, and in 1605, invested in a share of the parish tithes in Stratford.[54] 
Some of Shakespeare's plays were published in quarto editions, beginning in 1594, and by 1598, his name had become a selling point and began to appear on the title pages.[55][56][57] Shakespeare continued to act in his own and other plays after his success as a playwright. The 1616 edition of Ben Jonson's Works names him on the cast lists for Every Man in His Humour (1598) and Sejanus His Fall (1603).[58] The absence of his name from the 1605 cast list for Jonson's Volpone is taken by some scholars as a sign that his acting career was nearing its end.[47] The First Folio of 1623, however, lists Shakespeare as one of "the Principal Actors in all these Plays", some of which were first staged after Volpone, although we cannot know for certain which roles he played.[59] In 1610, John Davies of Hereford wrote that "good Will" played "kingly" roles.[60] In 1709, Rowe passed down a tradition that Shakespeare played the ghost of Hamlet's father.[35] Later traditions maintain that he also played Adam in As You Like It, and the Chorus in Henry V,[61][62] though scholars doubt the sources of that information.[63] 
Throughout his career, Shakespeare divided his time between London and Stratford. In 1596, the year before he bought New Place as his family home in Stratford, Shakespeare was living in the parish of St. Helen's, Bishopsgate, north of the River Thames.[64][65] He moved across the river to Southwark by 1599, the same year his company constructed the Globe Theatre there.[64][66] By 1604, he had moved north of the river again, to an area north of St Paul's Cathedral with many fine houses. There, he rented rooms from a French Huguenot named Christopher Mountjoy, a maker of ladies' wigs and other headgear.[67][68] 
Later years and death
 

Shakespeare's funerary monument in Stratford-upon-Avon
Rowe was the first biographer to record the tradition, repeated by Johnson, that Shakespeare retired to Stratford "some years before his death".[69][70] He was still working as an actor in London in 1608; in an answer to the sharers' petition in 1635, Cuthbert Burbage stated that after purchasing the lease of the Blackfriars Theatre in 1608 from Henry Evans, the King's Men "placed men players" there, "which were Heminges, Condell, Shakespeare, etc.".[71] However, it is perhaps relevant that the bubonic plague raged in London throughout 1609.[72][73] The London public playhouses were repeatedly closed during extended outbreaks of the plague (a total of over 60 months closure between May 1603 and February 1610),[74] which meant there was often no acting work. Retirement from all work was uncommon at that time.[75] Shakespeare continued to visit London during the years 1611–1614.[69] In 1612, he was called as a witness in Bellott v. Mountjoy, a court case concerning the marriage settlement of Mountjoy's daughter, Mary.[76][77] In March 1613, he bought a gatehouse in the former Blackfriars priory;[78] and from November 1614, he was in London for several weeks with his son-in-law, John Hall.[79] After 1610, Shakespeare wrote fewer plays, and none are attributed to him after 1613.[80] His last three plays were collaborations, probably with John Fletcher,[81] who succeeded him as the house playwright of the King's Men.[82] 
Shakespeare died on 23 April 1616, at the age of 52.[f] He died within a month of signing his will, a document which he begins by describing himself as being in "perfect health". No extant contemporary source explains how or why he died. Half a century later, John Ward, the vicar of Stratford, wrote in his notebook: "Shakespeare, Drayton, and Ben Jonson had a merry meeting and, it seems, drank too hard, for Shakespeare died of a fever there contracted",[83][84] not an impossible scenario since Shakespeare knew Jonson and Drayton. Of the tributes from fellow authors, one refers to his relatively sudden death: "We wondered, Shakespeare, that thou went'st so soon / From the world's stage to the grave's tiring room."[85][g] 
 

Holy Trinity Church, Stratford-upon-Avon, where Shakespeare was baptised and is buried
He was survived by his wife and two daughters. Susanna had married a physician, John Hall, in 1607,[86] and Judith had married Thomas Quiney, a vintner, two months before Shakespeare's death.[87] Shakespeare signed his last will and testament on 25 March 1616; the following day, his new son-in-law, Thomas Quiney was found guilty of fathering an illegitimate son by Margaret Wheeler, who had died during childbirth. Thomas was ordered by the church court to do public penance, which would have caused much shame and embarrassment for the Shakespeare family.[87] 
Shakespeare bequeathed the bulk of his large estate to his elder daughter Susanna[88] under stipulations that she pass it down intact to "the first son of her body".[89] The Quineys had three children, all of whom died without marrying.[90][91] The Halls had one child, Elizabeth, who married twice but died without children in 1670, ending Shakespeare's direct line.[92][93] Shakespeare's will scarcely mentions his wife, Anne, who was probably entitled to one-third of his estate automatically.[h] He did make a point, however, of leaving her "my second best bed", a bequest that has led to much speculation.[95][96][97] Some scholars see the bequest as an insult to Anne, whereas others believe that the second-best bed would have been the matrimonial bed and therefore rich in significance.[98] 
 

Shakespeare's grave, next to those of Anne Shakespeare, his wife, and Thomas Nash, the husband of his granddaughter
Shakespeare was buried in the chancel of the Holy Trinity Church two days after his death.[99][100] The epitaph carved into the stone slab covering his grave includes a curse against moving his bones, which was carefully avoided during restoration of the church in 2008:[101] 
Good frend for Iesvs sake forbeare,
To digg the dvst encloased heare.
Bleste be  man  spares thes stones,
And cvrst be he  moves my bones.[102][i] 
(Modern spelling: Good friend, for Jesus' sake forbear, / To dig the dust enclosed here. / Blessed be the man that spares these stones, / And cursed be he that moves my bones.) 
Some time before 1623, a funerary monument was erected in his memory on the north wall, with a half-effigy of him in the act of writing. Its plaque compares him to Nestor, Socrates, and Virgil.[103] In 1623, in conjunction with the publication of the First Folio, the Droeshout engraving was published.[104] 
Shakespeare has been commemorated in many statues and memorials around the world, including funeral monuments in Southwark Cathedral and Poets' Corner in Westminster Abbey.[105][106]`, "\n")
